services:
  - type: web
    name: htaso-umpire-eval
    env: python
    region: oregon
    rootDir: flask_app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False

databases:
  - name: htaso-db
    databaseName: htaso_eval_db
    user: htaso_user
    plan: free
